title: Resume
author: Nicholas Groke
email: nick.groke@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Personal resume and portfolio for Nicholas Groke

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
